baseurl = "/"
languageCode = "en-us"
title = "Atul Acharya"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-115461344-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/laventura"
    weight = 3


[params]
    description = "Atul Acharya on Artificial Intelligence, Deep Learning, Self Driving Cars, Product, Strategy and more."
    # footer link 
    footer = "(c) 2005 - Present [Atul Acharya](https://atul.fyi) "

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "python", "c", "swift"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "atul-box-logo3x.png"
    width = 80
    height = 50
    alt = "Logo"

